### ISSUE TITLE
Remove datasource and resource provider configuration

### ISSUE THREAD

**Issue by brutus333** [dell/terraform-provider-redfish#28]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of now the provider is using provider configuration as part of datasource and resource attributes to circumvent one endpoint per provider limitation.
However, a more Terraform like solution would rely on multiple providers and provider aliases: Terraform supports what is called multiple provider configuration via aliases: https://www.terraform.io/docs/language/providers/configuration.html#alias-multiple-provider-configurations

Terraform code will not look very nice since will be some repetition in the provider definition code but it will be more likely that the provider itself will continue to work. However, there are open issues on terraform project dealing with usage of for_each and count for providers code so probably there will be a fix in the near future.
For provider code duplication issue there are some other solutions like terragrunt.
 
### New or Affected Resource(s)

All datasources and resources are affected by this change

### Potential Terraform Configuration

```hcl
provider "redfish" {
    user = "john"
    password = "password"
    endpoint = "http://172.17.0.2"
    ssl_insecure = true
    alias = "bios1"
}
provider "redfish" {
    user = "john"
    password = "password"
    endpoint = "http://172.17.0.3"
    ssl_insecure = true
    alias = "bios2"
}

data "redfish_bios" "bios_1" {
  provider = redfish.bios1
}

data "redfish_bios" "bios_2" {
  provider = redfish.bios2
}

```

### References

* #0000

### Aditional comments

I already fixed the code to allow this, if you find it valuable I can make a PR.

I have to say that the provider code is simplified by using this pattern.

**Comment by mikeletux** [comment]
Hey @brutus333 ,

Thank you very much for taking the time to open this issue.

When we started this provider, the main idea was to help operators to provision a bunch of servers at the time. It is true we started writing this as you mentioned, using alias for the different servers.

It turns out that, when you want to provision 100 servers at the time, things got messy. 
The approach you're mentioning is clean when you're dealing with no more that 10 servers at the time, but gets messy when above that number.

The other way around. When provisioning few servers, the current approach is messy, since as you say, we have to include the *redfish* block inside each of the resources/datasources. But, when things start to grow, it is the best approach.

We had conversations with Hashicorp regarding this points, as it was one of the major issues we found when starting developing this. After a while, we managed to get feedback from one of their engineers and they proposed this way of operation. Maybe not the best one in the world, but it worked. In words from this engineers, "we were blazing the trail", since Terraform was thought to only speak with one endpoint (or few several using the alias approach).

I think we are keeping the way it is for now as per this Terraform limitation, hope it is not an inconvenience for you. Anyways, if Terraform gets upgraded with features that allow us to keep working this way but removing the *redfish* block from everywhere, we will more that happy to implement that 😄 

Best regards!
/Miguel
